import type { Metadata } from "next";
import SideBar from "../ui/side-bar";

import Header from "../ui/header";
import { getSessionData } from "../lib/actions";


export const metadata: Metadata = {
    title: "Chat App",
    description: "Generated by create next app",
};

export default async function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    const user = await getSessionData()
    return (
        <body className="flex h-screen overflow-hidden">
            <SideBar user={user} />
            <div className="flex flex-col w-3/4">
                <Header />
                {children}
            </div>
        </body>
    );
}